### ISSUE TITLE
Retrieve destroyed student VM

### ISSUE THREAD

**Issue by ghost** [Voulnet/training-schedule#1]
Hi there,
I attended your Attacking & Securing APIs course in the past (at Singapore).

Unfortunately, it seems I messed up my student VM.
Is there a way to provide me with a new instance of it?

**Comment by Voulnet** [comment]
Yes it is possible to do that! Give me an email address I can send you the link to.

**Comment by ghost** [comment]
@Voulnet sorry for the late response. I thought it wasn't possible, so I closed the issue. 
If you can, please send me the link to: 
ahmad.shafique.63@outlook.com

**Comment by Voulnet** [comment]
After double checking the Singapore course student list, I have discovered that you lied, and you're trying to trick me to obtain and pirate the course content.

Not only you are malicious, but extremely dumb as well. You will be reported.
